---
# ClusterSecretStore - Main Azure Key Vault
# Provides secrets to all namespaces via ExternalSecret resources
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
    
      vaultUrl: "https://rex5-cc-mz-prod-kv.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: platform-external-secrets
        namespace: rex5-cc-mz-k8s-external-secrets

---
# ClusterSecretStore - Secondary Key Vault (if applicable)
# Uncomment and configure if you have multiple vaults
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: azure-keyvault-secondary-store
# spec:
#   provider:
#     azurekv:
#       vaultUrl: "https://<SECONDARY_KEYVAULT_NAME>.vault.azure.net/"
#       authType: WorkloadIdentity
#       serviceAccountRef:
#         name: platform-external-secrets
#         namespace: rex5-cc-mz-k8s-external-secrets
