---
# ClusterSecretStore - Main Azure Key Vault
# Provides secrets to all namespaces via ExternalSecret resources
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
      # TODO: Replace with your Key Vault URL
      vaultUrl: "https://<KEYVAULT_NAME>.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets

---
# ClusterSecretStore - Secondary Key Vault (if applicable)
# Uncomment and configure if you have multiple vaults
# apiVersion: external-secrets.io/v1
# kind: ClusterSecretStore
# metadata:
#   name: azure-keyvault-secondary-store
# spec:
#   provider:
#     azurekv:
#       vaultUrl: "https://<SECONDARY_KEYVAULT_NAME>.vault.azure.net/"
#       authType: WorkloadIdentity
#       serviceAccountRef:
#         name: external-secrets
#         namespace: external-secrets
