---
# PushSecret - pushes the wildcard certificate to Azure Key Vault
# This allows the certificate to be shared across namespaces via ExternalSecret
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-wildcard-cert
  namespace: rex5-cc-mz-k8s-shared
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - name: azure-keyvault-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: wildcard-tls
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: wildcard-tls-cert  # Key Vault secret name
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: wildcard-tls-key   # Key Vault secret name
