---
# Wildcard Certificate - issued by cert-manager, stored in Key Vault
# The certificate is pushed to Key Vault via PushSecret
# and distributed to namespaces via ExternalSecret
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: shared
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.<DOMAIN>"  # TODO: Replace (e.g., *.rex5.ca)
    - "<DOMAIN>"    # TODO: Replace (e.g., rex5.ca)
