---
# ExternalSecret for Grafana admin credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: rex5-cc-mz-k8s-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rex5-cc-mz-k8s-azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      data:
        admin-user: "admin"
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana-admin-password

---
# ExternalSecret for Grafana OAuth (Authentik)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: rex5-cc-mz-k8s-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rex5-cc-mz-k8s-azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: grafana-oauth-client-id
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: grafana-oauth-client-secret
