---
# ExternalSecret - ArgoCD Git repository credentials (SSH key)
# This will eventually replace the manually created secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds
  namespace: rex5-cc-mz-prod-argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rex5-cc-mz-prod-azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:kevrex5/kubernetes.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-git-ssh-private-key
