---
# CZ Platform Applications
# Manages all platform infrastructure components for the CZ cluster
# Uses sync waves to ensure dependency ordering
#
# NOTE: This cluster uses Azure CNI Powered by Cilium. Cilium is managed by Azure.
# Hubble (observability) is deployed separately via Helm.

# ============================================================================
# Namespaces (sync wave -1 - created before all other resources)
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cz-platform-namespaces
  namespace: rex5-cc-mz-k8s-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-cz
  source:
    repoURL: git@github.com:kevrex5/kubernetes.git
    targetRevision: HEAD
    path: platform-cz/canadacentral/namespaces
  destination:
    server: 'https://rex5-cc-cz-prod.rex5-cc-cz-prod-aks.privatelink.canadacentral.azmk8s.io:443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# ============================================================================
# Hubble Observability (sync wave 0 - alongside Azure-managed Cilium)
# ============================================================================
# NOTE: This does NOT install Cilium - Azure manages that.
# This only deploys Hubble Relay + UI for network flow visibility.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cz-platform-hubble
  namespace: rex5-cc-mz-k8s-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-cz
  sources:
    # Helm chart (Cilium chart with only Hubble enabled)
    # NOTE: Match version to Azure-managed Cilium (see: az aks show --query currentKubernetesVersion)
    # AKS 1.31 = Cilium 1.16.x, AKS 1.32+ = Cilium 1.17.x
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.17.12
      helm:
        valueFiles:
          - $values/platform-cz/canadacentral/hubble/values.yaml
    # Values from Git
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      ref: values
    # NetworkPolicies
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      path: platform-cz/canadacentral/hubble
      directory:
        exclude: '{values.yaml,kustomization.yaml,README.md}'
  destination:
    server: 'https://rex5-cc-cz-prod.rex5-cc-cz-prod-aks.privatelink.canadacentral.azmk8s.io:443'
    namespace: kube-system  # Hubble runs alongside Cilium in kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# ============================================================================
# cert-manager (sync wave 1 - needed for certificates)
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cz-platform-cert-manager
  namespace: rex5-cc-mz-k8s-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-cz
  sources:
    # Helm chart
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.1  # Pinned version
      helm:
        valueFiles:
          - $values/platform-cz/canadacentral/cert-manager/values.yaml
    # Values from Git
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      ref: values
    # ClusterIssuers and other resources
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      path: platform-cz/canadacentral/cert-manager
      directory:
        exclude: '{values.yaml,kustomization.yaml}'
  destination:
    server: 'https://rex5-cc-cz-prod.rex5-cc-cz-prod-aks.privatelink.canadacentral.azmk8s.io:443'
    namespace: rex5-cc-cz-k8s-cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

---
# ============================================================================
# external-secrets (sync wave 2 - needed for secrets)
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cz-platform-external-secrets
  namespace: rex5-cc-mz-k8s-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-cz
  sources:
    # Helm chart
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.17.0  # Supports v1 API
      helm:
        valueFiles:
          - $values/platform-cz/canadacentral/external-secrets/values.yaml
    # Values from Git
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      ref: values
    # ClusterSecretStores
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      path: platform-cz/canadacentral/external-secrets
      directory:
        exclude: '{values.yaml,kustomization.yaml}'
  destination:
    server: 'https://rex5-cc-cz-prod.rex5-cc-cz-prod-aks.privatelink.canadacentral.azmk8s.io:443'
    namespace: rex5-cc-cz-k8s-external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

---
# ============================================================================
# Traefik (sync wave 3 - ingress controller)
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cz-platform-traefik
  namespace: rex5-cc-mz-k8s-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-cz
  sources:
    # Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 38.0.2  # Pinned version
      helm:
        valueFiles:
          - $values/platform-cz/canadacentral/traefik/values.yaml
    # Values from Git
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      ref: values
    # ExternalSecret, wildcard certificate
    - repoURL: git@github.com:kevrex5/kubernetes.git
      targetRevision: HEAD
      path: platform-cz/canadacentral/traefik
      directory:
        exclude: '{values.yaml,kustomization.yaml}'
  destination:
    server: 'https://rex5-cc-cz-prod.rex5-cc-cz-prod-aks.privatelink.canadacentral.azmk8s.io:443'
    namespace: rex5-cc-cz-k8s-traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
