---
# Root Application - Bootstrap entry point
# Apply this first: kubectl apply -f argocd/apps/root.yaml
# It manages all other ArgoCD apps (App-of-Apps pattern)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Root app uses default project for full access

  source:
    repoURL: https://github.com/<ORG>/<REPO>.git  # TODO: Replace with actual repo
    targetRevision: HEAD  # TODO: Pin to tag/branch for production
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
