---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-grafana
  namespace: rex5-cc-mz-k8s-authentik
  labels:
    blueprints.goauthentik.io/instantiate: "true"
data:
  grafana.yaml: |
    version: 1
    metadata:
      name: grafana-oidc
      labels:
        managed-by: blueprint
        app: grafana
    entries:
      # OAuth2/OIDC Provider (Authentik acts as IdP for Grafana)
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: Grafana OIDC
        attrs:
          name: Grafana OIDC
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: !Env GRAFANA_OIDC_CLIENT_ID
          client_secret: !Env GRAFANA_OIDC_CLIENT_SECRET

          signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]

          # Redirect URIs Grafana will use
          redirect_uris:
            - matching_mode: strict
              url: "https://grafana.rex5.ca/login/generic_oauth"

          # Token lifetimes
          access_token_validity: hours=1
          access_code_validity: minutes=1
          refresh_token_validity: days=30
          refresh_token_threshold: hours=1
          
          # Include claims in ID token
          include_claims_in_id_token: true

          # Scopes/claims
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]

          # OAuth2 settings
          issuer_mode: per_provider
          sub_mode: user_email
          logout_method: backchannel

      # Application that ties Grafana to the provider
      - model: authentik_core.application
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          slug: grafana
          group: Monitoring
          meta_launch_url: https://grafana.rex5.ca
          meta_description: Monitoring and Visualization System
          meta_publisher: Rex5
          meta_icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/grafana.svg
          open_in_new_tab: true
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, Grafana OIDC]]
          policy_engine_mode: any
