---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-espocrm
  namespace: rex5-cc-mz-k8s-authentik
  labels:
    blueprints.goauthentik.io/instantiate: "true"
data:
  espocrm.yaml: |
    version: 1
    metadata:
      name: espocrm-oidc
      labels:
        managed-by: blueprint
        app: espocrm
    entries:
      # OAuth2/OIDC Provider (Authentik acts as IdP for EspoCRM)
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: EspoCRM OIDC
        attrs:
          name: EspoCRM OIDC
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: !Env ESPOCRM_OIDC_CLIENT_ID
          client_secret: !Env ESPOCRM_OIDC_CLIENT_SECRET

          signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]

          # Redirect URIs EspoCRM will use
          redirect_uris:
            - matching_mode: strict
              url: "https://crm.rex5.ca/oauth-callback"

          # Token lifetimes
          access_token_validity: hours=1
          access_code_validity: minutes=1
          refresh_token_validity: days=30
          refresh_token_threshold: hours=1
          
          # Include claims in ID token
          include_claims_in_id_token: true

          # Scopes/claims
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]

          # OAuth2 settings
          issuer_mode: per_provider
          sub_mode: hashed_user_id
          logout_method: backchannel

      # Application that ties EspoCRM to the provider
      - model: authentik_core.application
        identifiers:
          slug: espocrm
        attrs:
          name: EspoCRM
          slug: espocrm
          group: Business
          meta_launch_url: https://crm.rex5.ca
          meta_description: Customer Relationship Management System
          meta_publisher: Rex5
          meta_icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/espocrm.svg
          open_in_new_tab: true
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, EspoCRM OIDC]]
          policy_engine_mode: any
