---
# ClusterIssuer - Let's Encrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@rex5.ca
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: ed4abb65-42ea-480a-a53c-aeeb0a09eeb6
            resourceGroupName: rex5-cc-mz-k8s-dns-rg
            hostedZoneName: rex5.ca
            environment: AzurePublicCloud
            managedIdentity:
              clientID: 08d54073-58ed-434a-b351-8c87a17a775a

---
# ClusterIssuer - Let's Encrypt Production (for real certificates)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@rex5.ca
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: ed4abb65-42ea-480a-a53c-aeeb0a09eeb6
            resourceGroupName: rex5-cc-mz-k8s-dns-rg
            hostedZoneName: rex5.ca
            environment: AzurePublicCloud
            managedIdentity:
              clientID: 08d54073-58ed-434a-b351-8c87a17a775a
